let str = "aaaa";console.log(typeof str);
let num = 1;console.log(typeof num);
let bool = true;console.log(typeof bool);
let n = null;console.log(typeof n)
let u = undefined;console.log(typeof u)
let array = [];console.log(typeof array)
let object = {};console.log(typeof object)
let fn = function() {};console.log(typeof fn)
let regexp = /^\d+$/;console.log(typeof regexp)
let date = new Date();console.log(typeof date)
